# file: roles/cic2/tasks/main.yml
---

- name: Install base packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - docker

- name: Start cic2
  command: docker run -d --rm -p 8080:8080 -e MONGODB_URI={{ vault_mongo_uri }} dischord01/cic2:03



