# file: roles/cic2/tasks/main.yml
---

- name: Install base packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - docker

- name: Start docker
  service: 
    name: docker 
    state: started 
    enabled: yes

- name: Start cic2
  docker_container:
    name: cic2
    image: dischord01/cic2:02
    state: started
    ports:
    - "8080:8080"


