---
- name: Deploy Azure Resources 
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - deploy

- name: Install nodejs app
  hosts: all
  become: yes
  roles:
  - epel  
  - mongodb 
  - nodejs  
  - nodejs_app
