---
- name: Deploy Azure Resources 
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - deploy


- name: Install Eclipse Che
  hosts: azure
  become: yes
  roles:
    - zsh
    - eclipse_che