---
- name: Deploy Azure Resources 
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - { role: deploy, tags: ['deploy'] }
    - { role: teardown, tags: ['teardown'] }

- name: Install Dev Environment
  hosts: azure_group
  become: yes
  vars:
   system_user: ansible
  roles:
    - zsh
    - eclipse_che