---
- name: Deploy Azure Resources 
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - { role: deploy, tags: ['deploy'] }
    - { role: teardown, tags: ['teardown'] }

- name: Install Eclipse Che
  hosts: linuxvm1
  become: yes
  roles:
    - zsh
    - eclipse_che